### ISSUE TITLE
Altering mirrorlist breaks image

### ISSUE THREAD

**Issue by codebling** [Thermi/docker-makepkg#3]
The mirror list is replace with `Server = http://172.16.33.1:8990` in the [Dockerfile](https://github.com/Thermi/docker-makepkg/blob/master/Dockerfile#L6). This breaks the docker build, since this server does not currently exists. 

If the mirror will be changed, it should be done before the package database is downloaded. Alternatively, simply removing the mirrorlist alterations fixed this for me. 
(i.e. remove `cat <(echo Server = http://172.16.33.1:8990) /etc/pacman.d/mirrorlist > foobar && mv foobar /etc/pacman.d/mirrorlist && ` from the dockerfile)

**Comment by Thermi** [comment]
The committed Dockerfile is just an example. You have to use containerBuilder.py to generate the right Dockerfile for your environment. See https://github.com/Thermi/docker-makepkg/blob/master/containerBuilder.py#L95
